paginator:
    path: /paginator
    controller: App\Controller\PageController::index
    
frontoffice:
    resource: routes/frontoffice.yaml
    trailing_slash_on_root: false
    prefix:
        es: /es
        ca: /ca
        en: /

backoffice:
    resource: routes/backoffice.yaml
    trailing_slash_on_root: false
    prefix: /backoffice