runroom_samples:
    resource: "@RunroomSamplesBundle/Resources/config/routing.yaml"

runroom_cookies:
    resource: "@RunroomCookiesBundle/Resources/config/routing.yaml"

course_tiered_pricing:
    prefix: /tiered-pricing
    resource: "@CourseTieredPricingBundle/config/routing.yaml"

# Must be the last one
runroom_basic_page:
    resource: "@RunroomBasicPageBundle/Resources/config/routing.yaml"
