service:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Course\TieredPricingBundle\:
        resource: '../*'
        exclude:
            - ../Entity/

    App\Course\TieredPricingBundle\Controller\:
        resource: '../Controller/'
        public: true
        tags: ['controller.service_arguments']

    app.course.tiered_pricing_service:
        class: App\Course\TieredPricingBundle\Service\TieredPricingService
