name: PR Deploy

on:
    issue_comment:
        types: [created]

jobs:
    slash-command:
        name: Slash Command
        runs-on: ubuntu-latest
        outputs:
            ref: ${{ fromJson(steps.request.outputs.data).head.ref }}
        steps:
            - id: request
              uses: octokit/request-action@v2.x
              with:
                  route: ${{ github.event.issue.pull_request.url }}
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - uses: xt0rted/slash-command-action@v2
              with:
                  command: deploy
                  reaction-type: rocket

    deploy:
        name: Deploy
        needs: slash-command
        uses: runroom/archetype-symfony/.github/workflows/deploy.yaml@hotfix/try-new-pr-comment
        with:
            environment: staging
            tag: pr-${{ github.event.issue.number }}
        secrets: inherit
